HardwareEFCore/HardwareEFCore/Models/Cart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HardwareEFCore.Models
{
    public class Cart
    {
        private List<CartLine> lineCollection = new List<CartLine>();

        public virtual void AddItem(Drive drive, int quantity)
        {
            CartLine line = lineCollection
                .Where(d => d.Drive.DriveId == drive.DriveId)
                .FirstOrDefault();

            if (line == null)
            {
                lineCollection.Add(new CartLine
                {
                    Drive = drive,
                    Quantity = quantity
                });
            }
            else
            {
                line.Quantity += quantity;
            }
        }

        public virtual void RemoveLine(Drive Drive) =>
            lineCollection.RemoveAll(l => l.Drive.DriveId == Drive.DriveId);

        public virtual void Clear() => lineCollection.Clear();

        public virtual IEnumerable<CartLine> Lines => lineCollection;
    }

    public class CartLine
    {
        public int CartLineId { get; set; }
        public Drive Drive { get; set; }
        public int Quantity { get; set; }
    }
}

HardwareEFCore/HardwareEFCore/Controllers/BuildOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HardwareEFCore.Models;
using Microsoft.AspNetCore.Mvc;

namespace HardwareEFCore.Controllers
{
    public class BuildOrderController : Controller
    {
        private IBuildOrderRepository repository;
        private Cart cart;

        public BuildOrderController(IBuildOrderRepository repoService, Cart cartService)
        {
            repository = repoService;
            cart = cartService;
        }

        public ViewResult List() => View(repository.BuildOrders.Where(bo => !bo.Shipped));

        [HttpPost]
        public IActionResult MarkShipped(int buildOrderId)
        {
            BuildOrder buildOrder = repository.BuildOrders.FirstOrDefault(bo => bo.BuildOrderId == buildOrderId);

            if (buildOrder != null)
            {
                buildOrder.Shipped = true;
                repository.SaveBuildOrder(buildOrder);
            }

            return RedirectToAction(nameof(List)); 
        }

        public ViewResult Checkout() => View(new BuildOrder());

        [HttpPost]
        public IActionResult Checkout(BuildOrder buildOrder)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                //Now we associate the CartLines with the Order
                buildOrder.Lines = cart.Lines.ToArray();
                repository.SaveBuildOrder(buildOrder);
                return RedirectToAction(nameof(Completed));
            }
            else
            {
                return View(buildOrder);
            }
        }

        public ViewResult Completed()
        {
            cart.Clear();
            return View();
        }
    }
}

HardwareEFCore/HardwareEFCore/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HardwareEFCore.Infrastructure;
using HardwareEFCore.Models;
using HardwareEFCore.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace HardwareEFCore.Controllers
{
    public class CartController : Controller
    {
        private IDriveRepository repository;
        private Cart cart;

        public CartController(IDriveRepository repo, Cart cartService)
        {
            repository = repo;
            cart = cartService;
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToActionResult AddToCart(int driveId, string returnUrl)
        {
            Drive drive = repository.Drives.FirstOrDefault(d => d.DriveId == driveId);

            if (drive != null)
            {
                cart.AddItem(drive, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToActionResult RemoveFromCart(int driveId, string returnUrl)
        {
            Drive drive = repository.Drives.FirstOrDefault(d => d.DriveId == driveId);

            if (drive != null)
            {
                cart.RemoveLine(drive);
            }

            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

HardwareEFCore/HardwareEFCore/Views/Cart/Index.cshtml
@model CartIndexViewModel

<h2>Your Cart</h2>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Quantity</th>
            <th>Item Manufacturer</th>
            <th>Item Model</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Drive.Manufacturer</td>
                <td class="text-left">@line.Drive.Model</td>
                <td>
                    <form asp-action="RemoveFromCart" method="post">
                        <input type="hidden" name="DriveId" value="@line.Drive.DriveId" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">
                            Remove
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Add More Parts</a>

    <a class="btn btn-primary" asp-action="Checkout" asp-controller="BuildOrder">
        Submit Build
    </a>
</div>