HardwareEFCore/HardwareEFCore/Components/CartSummaryViewComponent.cs
using HardwareEFCore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace HardwareEFCore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;

        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(cart);
        }  
    }
}

HardwareEFCore/HardwareEFCore/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using HardwareEFCore.Infrastructure;
using HardwareEFCore.Models;
using HardwareEFCore.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace HardwareEFCore.Controllers
{
    public class CartController : Controller
    {
        private IDriveRepository repository;
        private Cart cart;

        public CartController(IDriveRepository repo, Cart cartService)
        {
            repository = repo;
            cart = cartService;
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }

        public RedirectToActionResult AddToCart(int driveId, string returnUrl)
        {
            Drive drive = repository.Drives.FirstOrDefault(d => d.DriveId == driveId);

            if (drive != null)
            {
                cart.AddItem(drive, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToActionResult RemoveFromCart(int driveId, string returnUrl)
        {
            Drive drive = repository.Drives.FirstOrDefault(d => d.DriveId == driveId);

            if (drive != null)
            {
                cart.RemoveLine(drive);
            }

            return RedirectToAction("Index", new { returnUrl });
        }
    }
}

HardwareEFCore/HardwareEFCore/Controllers/ComputerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using HardwareEFCore.Models;
using HardwareEFCore.Models.ViewModels;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Web.Helpers;
using Microsoft.AspNetCore.Http;

namespace HardwareEFCore.Controllers
{
    public class ComputerController : Controller
    {
        private IComputerRepository computerRepo;
        private int pageSize = 10;

        public ComputerController(IComputerRepository computerRepo)
        {
            this.computerRepo = computerRepo;
        }

        public IActionResult List(int page = 1)
        {
            ComputerListViewModel vModel = new ComputerListViewModel();

            IEnumerable<Computer> computers = computerRepo.Computers
                .OrderBy(c => c.ComputerId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize);

            vModel.Computers = computers;
            PagingInfo pInfo = new PagingInfo()
            {
                CurrentPage = page,
                ItemsPerPage = pageSize,
                TotalItems = computerRepo.Computers.Count()
            };

            vModel.PagingInfo = pInfo;
            return View(vModel);
        }

        [HttpPost]
        public IActionResult UploadImage(Computer computer)
        {
            var photos = HttpContext.Request.Form.Files;
            if (photos != null)
            {
                foreach (var image in photos)
                {
                    if (image != null)
                    {
                        string imgName = Path.GetFileName(image.FileName);
                        string imgExt = Path.GetExtension(imgName);

                        FileStream file = new FileStream(@"C:\Users\Dylan\Documents\School\ASP\labRepos\asp_lab12\HardwareEFCore\HardwareEFCore\wwwroot\Images\" + imgName, FileMode.Create);
                        using(var ms = new MemoryStream())
                        {
                            image.CopyTo(ms);
                            ms.WriteTo(file);
                            file.Close();
                            ms.Close();

                            computer.ImagePath = "/Images/" + imgName;
                        }
                    computerRepo.SaveComputer(computer);
                    }
                }
            }
            else
            {
                return View("List");
            }

            return RedirectToAction("List");
        }

        [HttpPost]
        public IActionResult DeleteImage(int computerId)
        {
            Computer computer = computerRepo.Computers.FirstOrDefault(c => c.ComputerId == computerId);
            computer.ImagePath = null;
            computerRepo.SaveComputer(computer);

            return RedirectToAction("List");
        }
        
    }
}

HardwareEFCore/HardwareEFCore/Views/Shared/ComputerSummary.cshtml
@model Computer


<div class="well">
    <h2>@Model.Manufacturer  @Model.Model - @Model.Nickname</h2>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <td>CPU</td>
                <td>RAM</td>
                <td>Drive(s)</td>
                <td>Build Photo</td>
            </tr>
        </thead>


        <tr>
            @foreach (CPU cpu in Model.Cpus)
            {
                <td>@cpu.Manufacturer @cpu.Model</td>
            }
            <td>
                @foreach (RAM ram in Model.Ram)
                {
                    <p>@ram.Manufacturer @ram.Model</p><br />
                }
            </td>
            <td>
                @foreach (Drive d in Model.Drives)
                {

                    <p>@d.Manufacturer @d.Model @d.SizeInGB GB</p><br />
                }
            </td>
            <td>
                @if (Model.ImagePath != null)
                { 
                    <img src="@Model.ImagePath" alt="Computer photo" style="max-width: 350px; height:auto;" />

                    <div>
                        <form asp-action="DeleteImage" asp-controller="Computer" method="post" enctype="multipart/form-data">
                            <input type="hidden" asp-for="ComputerId" />
                            <button asp-action="DeleteImage" class="btn btn-sm btn-danger" type="submit">Delete Photo</button>
                        </form>
                    </div>
                }
                else
                {
                    <p>No photo of completed build has been uploaded</p>
                    <div id="upload-image" class="form-group">
                        <form asp-action="UploadImage" asp-controller="Computer" method="post" enctype="multipart/form-data">
                            <input type="hidden" asp-for="ComputerId" />
                            <input class="input input-sm pull-left" type="file" name="image" id="image-uploader" />
                            <button asp-action="UploadImage" class="btn btn-sm btn-success" type="submit">Upload Image</button>
                        </form>
                    </div>
                }
            </td>
        </tr>
    </table>
</div>

HardwareEFCore/HardwareEFCore/Views/Shared/DriveSummary.cshtml
@model Drive

<div class="well" style="padding-bottom:35px;">
    <h3>
        <strong>@Model.Manufacturer @Model.Model</strong><br />
    </h3>
    <span class="lead">
        Interface: @Model.Interface <br />
        Transfer Protocol: @Model.TransferProtocol <br />
        Storage Capacity: @Model.SizeInGB GB <br />
    </span>
        
    <form id="@Model.DriveId" asp-action="AddToCart"
        asp-controller="Cart" method="post">

        <input type="hidden" asp-for="DriveId" />
        <input type="hidden" name="returnURL"
            value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                
        <button type="submit" class="btn btn-success btn-sm pull-right">
            Add to Build
        </button>

    </form>
        
    
</div>

HardwareEFCore/HardwareEFCore/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="~/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <script src="~/jquery/jquery.js"></script>
    <script src="~/jquery-validate/jquery.validate.js"></script>
    <script src="~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <title>@ViewBag.Title</title>
    <style>
        .input-validation-error {
            border-color: red;
            background-color: #fee;
        }
    </style>
</head>
<body class="panel panel-default">
    <div class="panel-heading"><h4>@ViewBag.Title</h4></div>
    <div class="panel-body">
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }

        @RenderBody()
    </div>
</body>
</html>

HardwareEFCore/HardwareEFCore/Views/Shared/_Layout.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>PC Hardware</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <link href="~/font-awesome/css/font-awesome.css" rel="stylesheet" />

</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">PC BUILDER</a>

        <div class="pull-right">
            @await Component.InvokeAsync("CartSummary")
        </div>
    </div>

    <div class="row panel">
        <div id="categories" class="col-xs-3 dropdown show">
            <a class="btn btn-default btn-block dropdown-toggle" href="/Computer">Computers</a><br />
            <div class="dropdown">
                <button type="button" class="btn btn-default btn-block dropdown-toggle" id="dropDownMenu1" data-toggle="dropdown">Drives <span class="caret"></span></button>
                <ul id="interfaceFilter" class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenu1">
                    @await Component.InvokeAsync("NavigationMenu")
                </ul>
            </div>
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>
</body>
</html>